name: Simple CI with Security Scan 
on: 
  push: 
    branches: [ main ] 

jobs: 
  build-and-scan: 
    runs-on: ubuntu-latest 

  steps: 
  - name: Checkout code 
  uses: actions/checkout@v3 
  
  steps:
  - name: Set up Docker
  uses: docker/setup-buildx-action@v3 
  
  steps:
  - name: Build Docker image 
  run: docker build -t myapp:latest . 

  steps:
  - name: Run Trivy vulnerability scanner 
  uses: aquasecurity/trivy-action@master 
  with: 
    image-ref: 'myapp:latest' 
    format: 'table' 
    ignore-unfixed: true 
    severity: 'CRITICAL,HIGH' 